CREATE TABLE FINANCIAL_GOAL(
Goal VARCHAR(200),
Phone VARCHAR(15),
Amount FLOAT,
Timeline VARCHAR(100),
PRIMARY KEY(Goal,Phone)
);

CREATE TABLE RISK_TOLERANCE(
Risk_Level VARCHAR(30),
Phone VARCHAR(15),
Q1_Answer VARCHAR(100),
Q2_Answer VARCHAR(100),
Q3_Answer VARCHAR(100),
Q4_Answer VARCHAR(100),
Q5_Answer VARCHAR(100),
PRIMARY KEY(Risk_Level,Phone)
);

CREATE TABLE INVESTOR(
Phone VARCHAR(15),
I_Name VARCHAR(30),
Gender VARCHAR(10),
DoB DATE,
Annual_Income FLOAT,
Company VARCHAR(100),
PRIMARY KEY(Phone)
);

CREATE TABLE PORTFOLIO_1(
P_ID VARCHAR(15),
Phone VARCHAR(15),
Market_Value FLOAT,
Inception_Date DATE,
PRIMARY KEY(P_ID,Phone)
);

CREATE TABLE PORTFOLIO_2(
Market_Value FLOAT,
Inception_Date DATE,
Annualized_Return FLOAT,
PRIMARY KEY(Market_Value,Inception_Date)
);

CREATE TABLE PORTFOLIO_3(
Fee FLOAT,
Market_Value FLOAT,
Annualized_Return FLOAT,
PRIMARY KEY(Market_Value,Annualized_Return)
);

CREATE TABLE INVESTED_VALUE(
I_Date DATE,
P_ID VARCHAR(15),
Phone VARCHAR(15),
Amount FLOAT,
PRIMARY KEY(I_Date,P_ID,Phone)
);

CREATE TABLE UNREALIZED_GAIN_LOSS(
GL_Date DATE,
P_ID VARCHAR(15),
Phone VARCHAR(15),
Amount FLOAT,
PRIMARY KEY(GL_Date,P_ID,Phone)
);

CREATE TABLE STOCK_IN_PORTFOLIO_1(
ID VARCHAR(15),
Start_Date DATE,
Post_Trade_CO VARCHAR(100),
PID VARCHAR(15),
Phone VARCHAR(15),
Stock_ID VARCHAR(15),
PRIMARY KEY(ID)
);

CREATE TABLE STOCK_IN_PORTFOLIO_2(
Allocation_Ratio FLOAT,
PID VARCHAR(15),
Phone VARCHAR(15),
PRIMARY KEY(Phone,PID)
);

CREATE TABLE BOND_IN_PORTFOLIO_1(
ID VARCHAR(15),
Start_Date DATE,
Post_Trade_CO VARCHAR(100),
PID VARCHAR(15),
Phone VARCHAR(15),
Bond_ID VARCHAR(15),
PRIMARY KEY(ID)
);

CREATE TABLE BOND_IN_PORTFOLIO_2(
Allocation_Ratio FLOAT,
PID VARCHAR(15),
Phone VARCHAR(15),
PRIMARY KEY(Phone,PID)
);

CREATE TABLE FUND_IN_PORTFOLIO_1(
ID VARCHAR(15),
Start_Date DATE,
Post_Trade_CO VARCHAR(100),
PID VARCHAR(15),
Phone VARCHAR(15),
Fund_ID VARCHAR(15),
PRIMARY KEY(ID)
);

CREATE TABLE FUND_IN_PORTFOLIO_2(
Allocation_Ratio FLOAT,
PID VARCHAR(15),
Phone VARCHAR(15),
PRIMARY KEY(Phone,PID)
);

CREATE TABLE STOCK_TRANSACTION(
T_Date DATE,
Stock_In_Portfolio_ID VARCHAR(15),
T_Type VARCHAR(15),
Fee FLOAT,
PRIMARY KEY(T_Date,Stock_In_Portfolio_ID)
);

CREATE TABLE BOND_TRANSACTION(
T_Date DATE,
Bond_In_Portfolio_ID VARCHAR(15),
T_Type VARCHAR(15),
Fee FLOAT,
PRIMARY KEY(T_Date,Bond_In_Portfolio_ID)
);

CREATE TABLE FUND_TRANSACTION(
T_Date DATE,
Fund_In_Portfolio_ID VARCHAR(15),
T_Type VARCHAR(15),
Fee FLOAT,
PRIMARY KEY(T_Date,Fund_In_Portfolio_ID)
);

CREATE TABLE ASSET(
ID VARCHAR(15),
A_Name VARCHAR(30),
Price FLOAT,
PRIMARY KEY(ID)
);

CREATE TABLE STOCK(
ID VARCHAR(15),
P_E_Ratio FLOAT,
EPS FLOAT,
EBITDA FLOAT,
PRIMARY KEY(ID)
);

CREATE TABLE BOND(
ID VARCHAR(15),
Interest_Rate FLOAT,
Maturity_Date DATE,
PRIMARY KEY(ID)
);

CREATE TABLE FUND(
ID VARCHAR(15),
Expense_Ratio FLOAT,
Dividend_Yield FLOAT,
PRIMARY KEY(ID)
);